RigsOfRods/docs.rigsofrods.org

legal/crash-report-privacy-policy.md

Part of https://github.com/RigsOfRods/rigs-of-rods/pull/1248

Added Crash Report Privacy Policy

---

gameplay/controls-config.md

See #12 for more info.
Also updated the "How to contribute input maps" section with the new RoRConfig device info.

Controls page update v2

---

tools-tutorials/blender-beginner.md

Fixed more images + Old wiki link

More BlenderBeginner fixes

---

vehicle-creation/fileformat-truck.md

I always find myself having to replace the -1's (default values) with
the actual values. So I added a extra line with all the default options
already set.

Added SBD line with default values

---

vehicle-creation/fileformat-truck.md
vehicle-creation/suspension.md

Fixed images in suspension page, replaced placeholder "wikilinks"  in truck file format page.

Various late night fixes

---

vehicle-creation/fileformat-truck.md

- Added example for multiple options with node mass.
- Added documentation for the `wheeldetachers` section.

Truck file format page improvements

---

gameplay/jargon.md

Fixed Jargon formatting

---

download/suspension-demo-mcpherson-using-slidenodes.truck

RoR seems to have an issue with descriptions that have multiple lines. Need to do more testing.

Fixed RoR crashing when spawning example truck

---

gameplay/multiplayer-server-setup.md

This is what happens when you're tired.

Multiplayer setup - fixed typo

---

gameplay/multiplayer-server-setup.md

2.38/2.37 servers have UserAuth support by default now.

Multiplayer setup - Updated UserAuth info

---

oldwiki-done.md
oldwiki-todo.md
terrain-creation/shadows.md

Added PSSM shadows page from https://archives.rigsofrods.org/wiki/index.php/Shadows.

Added Shadows page

---

vehicle-creation/fileformat-truck.md
vehicle-creation/wheels-axles-steering.md

Also improved the wheels/axles/steering page. fixes #49

Fixed `Liquid warnings`

---

vehicle-creation/engine.md

Replaced HTML with Markdown and some other typo fixes.
Also @only-a-ptr can you please give me administrator access to this repo so I can set up the Discord webhook? Thanks.

Reworked engine page

---

vehicle-creation/alternate-skins.md

- Fixed typos and syntax errors
- Improved formatting
- Fixed outdated info, added example skin link

Updated `Making alternate skins` page

---

gameplay/general-faq.md

- Fixed quote bleeding onto the TOC
- Changed wording on old forum account question
- Moved installing content section above website/forum, separated from archive links
- Removed dead content pack links
- Removed space before beginning of question and answer
- Added 2 more questions/answers

General FAQ improvements

---

gameplay/jargon.md

- Added TOC
- Removed <!-> lines
- Moved Props above Flexbody

Updated Jargon page

---

vehicle-creation/rail-vehicles.md

- Fixed links
- Added inline code blocks where needed
- Removed outdated "high quality reflections" crash info
- Removed old forum link

Improved "building rail vehicles" page

---

gameplay/controls-config.md

Added headers to the input mapping tutorial for easier linking.

Added headers to input mapping tool tutorial

---

vehicle-creation/fileformat-truck.md

Reference: https://github.com/RigsOfRods/rigs-of-rods/pull/1597

Updated AntiLockBrakes & TractionControl sections

---

terrain-creation/collision-meshes.md
terrain-creation/terrain-conversion-terrn2.md
vehicle-creation/tracked-vehicles.md

- Fixed more links in terrn2 conversion page
- Removed dead link in tracked vehicles page
- Added TOC and improved formatting in collision meshes page

Various page fixes

---

oldwiki-done.md
oldwiki-todo.md
vehicle-creation/fileformat-truck.md

- Added extra info to `axles`/`interaxles`/`transfercase` sections to hopefully prevent future confusion
- Changed version syntax to be consistent 
- Fixed links on old wiki done/todo pages

Clarified axles/interaxles/transfercase sections + Fixed old wiki page links

---

gameplay/multiplayer-server-setup.md

- Changed `Development builds` to `0.4.8.0`
- Added pre-built packages for 0.4.8.0
- Added quick setup sections 
- Various other formatting improvements

[MP Server Setup] Updated for 0.4.8.0

---

tools-tutorials/visual-editors.md

Will update for the latest Blender plugins later.

[Visual Editors] Fixed links

---

tools-tutorials/visual-editors.md

update to link in line 22(blank truck file template) link should now direct users to appropriate file.

Update to link

---

vehicle-creation/motorbikes.md

Removed link for old forum that does not exist. Line 14

update to motorbikes

---

gameplay/controls-config.md

Fixed typos and added extra keys.

[Controls] Some improvements

---

gameplay/installing-content.md

e.g. the Gabester Vehicle Pack or the content packs.

[Installing Content] Added section on installing content packs

---

terrain-creation/shadows.md

Just some cleanups. Plan on doing more later.

Cleaned up shadows page

---

scripts/json2.js
vehicle-creation/flexbody-wheels.md

This is the flexbody wheel generator from http://nmurdoch.ca/flexbodywheels.html. Ported to the docs for preservation and to provide a more detailed explanation.

Added flexbody wheel generator

---

gameplay/multiplayer-server-setup.md

Clarify the port protocol is TCP and make the router section into a notice.

Clarifications

---

source/terrain-creation/race-generator.md
source/vehicle-creation/flexbody-wheels.md

Theme fixes

---

source/stylesheets/ror.css

Old: 
New:
Maybe I should investigate into mkdocs and see if it supports sass.

Fixed footer theme

---

source/vehicle-creation/making-custom-hud.md

Updated warning box to reflect current development: https://github.com/RigsOfRods/rigs-of-rods/pull/2764
Added some missing inputs

"Custom HUD" page updates

---

source/terrain-creation/terrn2-subsystem.md

Forward update for v2022l.04 release.

Terrn2: marked "AmbientColor" unused

---

dictionary/en-custom.txt
source/vehicle-creation/fileformat-soundscript.md
source/vehicle-creation/fileformat-truck.md
source/vehicle-creation/wheels-axles-steering.md

- Added missing sound sources
- Fixed axles and hydros example code
- Added note on setting extcamera manually by middle-clicking

Soundscript updates

---

source/terrain-creation/l3dt-map-making.md

- Updated wording of a few things
- GIMP includes DDS plugin as of 2.10.10, updated requirements 
- Added note about L3DT being freeware now

[L3DT Map Making] Small updates

---

source/vehicle-creation/fileformat-truck.md

Added dashboard indicator `d` flare type to truck file format.

Added dashboard indicator `d` flare type

---

dictionary/en-custom.txt
mkdocs.yml
source/README.md
source/tools-tutorials/docs-contributing-guide.md

Updated the contribution guide for the docs, and re added the quick edit button on all pages.

📝 Updated the docs contribution guide

---

dictionary/en-custom.txt
mkdocs.yml
source/README.md
source/gameplay/installing-the-game.md
source/tools-tutorials/docs-contributing-guide.md

This updates the install guide to better cover different approaches to installing the game both on Windows and Linux.

Updated install guide
